version: "3"
services:

  react:
    container_name: react
    build:
      context: ./client
      dockerfile: react-dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  node:
    container_name: node
    build:
      context: ./server
      dockerfile: node-dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - '4001:4000'

  database:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test-one
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  
volumes:
  pgdata:
