version: "3"
services:

  node-react:
    container_name: node-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  database:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test-one
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  
volumes:
  pgdata:
